# Generated by Django 4.0 on 2022-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_pagetreenode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageelement",
            name="children",
        ),
        migrations.AddField(
            model_name="pageelement",
            name="children",
            field=models.ManyToManyField(to="app.PageElement"),
        ),
        migrations.AlterField(
            model_name="pageelement",
            name="last_edited",
            field=models.DateTimeField(),
        ),
    ]
