# Generated by Django 4.0 on 2022-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_pageelement_children_pageelement_children_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetreenode",
            name="url",
            field=models.CharField(db_index=True, default=None, max_length=30, null=True),
        ),
    ]
