# Generated by Django 4.0 on 2022-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_pageelement_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetreenode",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
