# Generated by Django 4.0 on 2022-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pagetreenode_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerenderedPageElement',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('content', models.JSONField()),
            ],
        ),
    ]
