# Generated by Django 4.1 on 2023-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_pageelement_type_alter_pagetreenode_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="prerenderedpageelement",
            name="text_content",
            field=models.TextField(default=""),
        ),
    ]
