# Generated by Django 4.1 on 2023-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_prerenderedpageelement_guide_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prerenderedpageelement",
            name="nodes_trace",
            field=models.JSONField(default={}),
        ),
    ]
