# Generated by Django 4.1 on 2023-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_prerenderedpageelement_nodes_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prerenderedpageelement",
            name="nodes_trace",
            field=models.JSONField(default=dict),
        ),
    ]
