name: Guides API deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_USERNAME }}
        password: ${{ secrets.API_SERVER_PASSWORD }}
        script: |
          cd ${{ secrets.API_SERVER_FOLDER }}/manuals
          git checkout main
          git fetch
          git reset --hard origin/main
          git clean -df
          git pull

          docker compose up -d --build
